name: CherokeeTrainingData
channels:
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - audioread=2.1.9
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - cryptography=35.0.0
  - cudatoolkit=11.1.1
  - curl=7.71.1
  - cycler=0.11.0
  - dbus=1.13.6
  - decorator=5.1.0
  - expat=2.4.1
  - ffmpeg=4.3.2
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - git=2.32.0
  - gitdb=4.0.9
  - gitpython=3.1.24
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.1
  - intel-openmp=2021.3.0
  - jbig=2.1
  - joblib=1.1.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libffi=3.3
  - libflac=1.3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libogg=1.3.4
  - libopenblas=0.3.17
  - libopus=1.3.1
  - libpng=1.6.37
  - librosa=0.8.1
  - libsndfile=1.0.31
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libuv=1.42.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - llvmlite=0.36.0
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2021.3.0
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - numba=0.53.1
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1l
  - packaging=21.2
  - pcre=8.45
  - pcre2=10.35
  - perl=5.32.1
  - pillow=7.2.0
  - pip=21.2.4
  - pooch=1.5.2
  - progressbar=2.5
  - pthread-stubs=0.4
  - pycparser=2.20
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - pysoundfile=0.10.3.post1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.8.2
  - qt=5.9.7
  - readline=8.1
  - requests=2.26.0
  - resampy=0.2.2
  - scikit-learn=0.24.2
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - smmap=3.0.5
  - sqlite=3.36.0
  - threadpoolctl=3.0.0
  - tk=8.6.10
  - tornado=6.1
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - urllib3=1.26.7
  - wheel=0.37.0
  - x264=1!161.3030
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - colorlog==6.4.1
    - denoiser==0.1.4
    - hydra-colorlog==0.1.4
    - hydra-core==0.11.3
    - numpy==1.21.2
    - omegaconf==1.4.1
    - pydub==0.25.1
    - pystoi==0.3.3
    - pyyaml==5.4.1
    - scipy==1.7.1
    - sounddevice==0.4.2
    - torch==1.9.1
    - torchaudio==0.9.1
    - torchlibrosa==0.0.7
    - voicefixer==0.0.16
